//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QurankuWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QurankuWPF.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asr.
        /// </summary>
        public static string Asr {
            get {
                return ResourceManager.GetString("Asr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change location.
        /// </summary>
        public static string ChangeLocation {
            get {
                return ResourceManager.GetString("ChangeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhuhr.
        /// </summary>
        public static string Dhuhr {
            get {
                return ResourceManager.GetString("Dhuhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding location....
        /// </summary>
        public static string FindingLocation {
            get {
                return ResourceManager.GetString("FindingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find my location.
        /// </summary>
        public static string FindLocation {
            get {
                return ResourceManager.GetString("FindLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to find location manually.
        /// </summary>
        public static string FindLocationAlternative {
            get {
                return ResourceManager.GetString("FindLocationAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, there is a problem when we try to find your location. Please make sure to enable &quot;Location&quot; on your device and Quranku is given access to your location in Settings..
        /// </summary>
        public static string FindLocationDenied {
            get {
                return ResourceManager.GetString("FindLocationDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can try to find your location manually.
        /// </summary>
        public static string FindLocationDeniedAlternative {
            get {
                return ResourceManager.GetString("FindLocationDeniedAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Denied.
        /// </summary>
        public static string FindLocationDeniedTitle {
            get {
                return ResourceManager.GetString("FindLocationDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isha.
        /// </summary>
        public static string Isha {
            get {
                return ResourceManager.GetString("Isha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maghrib.
        /// </summary>
        public static string Maghrib {
            get {
                return ResourceManager.GetString("Maghrib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need your location to know the prayer time in your place.
        /// </summary>
        public static string NoLocationSpecified {
            get {
                return ResourceManager.GetString("NoLocationSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Location Settings.
        /// </summary>
        public static string OpenLocationSettings {
            get {
                return ResourceManager.GetString("OpenLocationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prayer Time.
        /// </summary>
        public static string PrayerTimePageTitle {
            get {
                return ResourceManager.GetString("PrayerTimePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shubuh.
        /// </summary>
        public static string Shubuh {
            get {
                return ResourceManager.GetString("Shubuh", resourceCulture);
            }
        }
    }
}
